#!/usr/bin/bash

PATH=/opt/local/gnu/bin:/opt/local/bin:/opt/local/sbin:/usr/bin:/usr/sbin

# Exit if any command fails
set -o errexit

MUNIN_PLUGINS="
	apache_accesses
	apache_processes
	apache_volume
	httpd_memory
	passenger_status
	passenger_memory
	ps_httpd
	ps_delayed_job
	dj_queue
"

echo "* Activate munin plugins"
/opt/qutic/bin/munin-node-plugins ${MUNIN_PLUGINS}

echo "* Remove unused httpd config files"
HTTPD_CONF_RM="httpd-autoindex.conf
httpd-dav.conf
httpd-default.conf
httpd-info.conf
httpd-languages.conf
httpd-manual.conf
httpd-mpm.conf
httpd-multilang-errordoc.conf
httpd-ssl.conf
httpd-userdir.conf
httpd-vhosts.conf"

for CONF_RM in ${HTTPD_CONF_RM}; do
  rm -f /opt/local/etc/httpd/${CONF_RM}
done

echo "* Setup ruby env"

echo "gem: --no-document " >> /opt/local/etc/gemrc
gem update --system
gem install bundler
gem install gemenv
gem install pkg-config

echo "* Setup ruby home"
groupadd -g 1100 ruby
useradd -m -s /usr/bin/bash -d /home/ruby -u 1100 -g ruby ruby
passwd -N ruby
passwd -d ruby

cat >> /home/ruby/.bashrc << EOF
source /home/ruby/www/shared/gems/bin/activate
EOF
cat >> /home/ruby/.bash_history << EOF
#`date +'%s'`
cd /home/ruby/www/current
EOF

mkdir -p /home/ruby/www/releases
mkdir -p /home/ruby/www/shared/config
mkdir -p /home/ruby/www/shared/content
mkdir -p /home/ruby/www/shared/log
mkdir -p /home/ruby/www/shared/system
cd /home/ruby/www/shared
/opt/local/bin/gemenv gems

mv /opt/local/var/tmp/activate /home/ruby/www/shared/gems/bin/activate
mv /opt/local/var/tmp/ruby /home/ruby/www/shared/gems/bin/ruby
chmod +x /home/ruby/www/shared/gems/bin/ruby
chown -R ruby:ruby /home/ruby

# Configuring image specific packages
echo "* Configuring image specific packages.";
mkdir -p /var/log/httpd/old
mkdir -p /opt/local/etc/httpd/ssl || true
chmod 0640 /opt/local/etc/httpd/ssl
ln -nfs /opt/local/etc/httpd/ssl /opt/local/etc/httpd/tls

echo "* Fix passenger";
echo "export PASSENGER_INSTANCE_REGISTRY_DIR=/var/tmp" >> /root/.bashrc
# fix wrong passenger pkgsrc build 2017Q4 for ruby 2.7
ln -nfs /opt/local/lib/ruby/vendor_ruby/2.7.0 /opt/local/lib/ruby/vendor_ruby/2.2.0

echo "* Import ruby process watcher";
svccfg import /opt/qutic/lib/svc/manifest/rbpswatch.xml
# svcadm enable rbpswatch

echo "* Add plugin config";
cat >> /opt/local/etc/munin/plugin-conf.d/dj_queue << EOF
[dj_queue]
env.PATH /usr/local/sbin:/usr/local/bin:/opt/local/sbin:/opt/local/bin:/usr/sbin:/usr/bin:/sbin
user ruby
EOF

echo "* Add squoosh with cli";
npm i -g squoosh
npm i -g @squoosh/cli

# Clean up
echo "* Cleaning up."
#pkgin -y remove gmake
#pkgin -y remove gcc7
rm /root/customize
rm -rf /opt/local/var/tmp

# Prepare image for provisioning
sm-prepare-image -y
